### ISSUE TITLE
Event does not exist. (PAPI_ENOEVNT)

### ISSUE THREAD

**Issue by frankicia** [flozz/pypapi#17]
When trying to use the papi_low interface, I get the following error:

```
>>> papi.add_event(evs, events.PAPI_FP_OPS)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bsc18/bsc18833/packages/pypapi/pypapi/exceptions.py", line 170, in papi_error_wrapper
    raise object_()
pypapi.exceptions.PapiNoEventError: Event does not exist. (PAPI_ENOEVNT)
```

Same issue when trying to use the papi_high interface.

My current system is:
Python 3.6.5
OS is Red Hat Enterprise Linux Server 7.5
POWER9 (ppc64le) architecture

**Comment by flozz** [comment]
Hello,

This mean that the event you are trying to add is not available on you system (the hardware or your OS/Kernel does not support it).

I can not help you further as this project is only a Python binding of the PAPI C Library. Maybe you will find more help in the original doc (https://icl.utk.edu/papi/index.html) or by contacting the developers of the library (https://icl.utk.edu/papi/custom/index.html?lid=50&slid=67)

:)

**Comment by AdrienBenamira** [comment]
Hello @frankicia did you find how to fix the error ?

Best,

Adrien

**Comment by undertherain** [comment]
I have the same problem. Hovewer, system's `papi_avail` reports that plenty of counters are available
I think one possible issue is that that python_papi is using own version of papi or compiling it in some wrong way

**Comment by flozz** [comment]
It is possible that one of required counter is not available. We were able to make this Python binding work on some machine, but it does not work on other.... If you find any information about PAPI compilation that make it work on more hardware, let me know, it would be a great improvement :D

**Comment by asalarian** [comment]
I had the same issue and found out the reason was access to the PMUs is blocked by default in Linux. Here is a discussion and solution to the problem (https://stackoverflow.com/questions/32308175/papi-avail-no-events-available)

**Comment by flozz** [comment]
I close the issue as there is no more activity. :)
