### ISSUE TITLE
ImportError: cannot import name 'papi_high' from 'pypapi' (unknown location)

### ISSUE THREAD

**Issue by mickymount** [flozz/pypapi#23]
Hi pypapi team,

Thanks for your work on this! I am trying to use pypapi in a project I am working on, however I turn to be facing issues doing so. I successfully installed the package in a python vm and when I import it in python repl that worked without any issues. However, when I run the script with the same import I get the listed error. 
The following steps may help narrow down any possible suggestion:

1.  python -m venv vmnane
2. . vmname/bin/activate
3. CC=gcc pip install python_papi (installed python-papi==5.5.1.5 version)
4. python
5. from pypapi import papi_high (works without any issue)

But in script.py step 5 doesn't see where pypapi is located. Thanks and I hope you could help me troubleshoot this error.

**Comment by flozz** [comment]
Hello,

To try to reproduce your issue, I have some questions:

* What is you OS / Linux distribution?
* What Python version are you using?
* How do you run `script.py` (`./script.py` or `python script.py`)?
* Do you run it from the activated venv?

**Comment by mickymount** [comment]
Hello,

Thanks for the quick response.

OS/Linux distribution:
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.8.2003 (Core)
Release:	7.8.2003
Codename:	Core

Python version: Python 3.7.6 (default, Jan  8 2020, 19:59:22) initially I tried intel distribution for python, I never got pass installing the package and then I reverted to regular python.

How script.py is run: ./script.py 

Venv:

I do submit a slurm job with

module load hdf5/1.10.1

source torchvenv/bin/activate

./script.py

Thanks and I hope this helps,

**Comment by flozz** [comment]
as you run the script using `./script.py` can you give me the shebang (the first line of the script that starts with `#!`).

I will try to reproduce on my Ubuntu, and if I can't I will try in a CentOS VM

**Comment by mickymount** [comment]
I just changed fro
#!/shared/centos7/intel/parallel_studio_xe_2020_update2_cluster_edition/c6420/intelpython3/bin/python
to 
#!/usr/bin/env python 
and it worked but its trowing PapiNoEventError

Traceback (most recent call last):
  File "./torchsgd.py", line 20, in <module>
    papi_events.PAPI_TOT_CYC
  File "torchvenv/lib/python3.7/site-packages/pypapi/exceptions.py", line 170, in papi_error_wrapper
    raise object_()
pypapi.exceptions.PapiNoEventError: Event does not exist. (PAPI_ENOEVNT) 

but the documentation says there is an event call PAPI_TOT_CYC

**Comment by flozz** [comment]
It is now a more useful message :dagger: 

The `PAPI_ENOEVNT` error means that the event you want to listen is not available on your system (but there is not much information on the PAPI doc about it...)

You can ask for help on the PAPI project, they should be more helpful on this :) 

https://icl.utk.edu/papi/custom/index.html?lid=50&slid=67

**Comment by flozz** [comment]
Oh there I looked at other issues we have, you might find more info on #17 too :)

**Comment by mickymount** [comment]
Thanks for your help, this is more helpful!

**Comment by fotisdr** [comment]
Hello,

Has anyone found a workaround for the `PAPI_ENOEVNT` error so far? I've installed pypapi on 4 different computers and I get the same error when trying to count the FLOPs.

**Comment by flozz** [comment]
@fotisdr maybe this could help you : https://stackoverflow.com/questions/32308175/papi-avail-no-events-available

**Comment by fotisdr** [comment]
> @fotisdr maybe this could help you : https://stackoverflow.com/questions/32308175/papi-avail-no-events-available

Hi flozz,
I have tried this but it didn't make any difference, I still can't measure the FLOPS with the FP_OPS event. Also, when I use the DP_OPS event to count the operations of a CNN (which works on most of the computers I tested it) I get really low FLOPS (like 400 for a pretty big auto-encoders), is this normal?

**Comment by flozz** [comment]
> I have tried this but it didn't make any difference, I still can't measure the FLOPS with the FP_OPS event.

Ok I have no more idea then...

> Also, when I use the DP_OPS event to count the operations of a CNN (which works on most of the computers I tested it) I get really low FLOPS (like 400 for a pretty big auto-encoders), is this normal?

I do not know.

----

I just made a Python binding of PAPI to help someone, and I do not used it so much after... I think you should ask PAPI's developers, they may help you better for PAPI related questions; I can just help you on PAPI←→Python questions.

**Comment by fotisdr** [comment]
Okay, I will probably contact the PAPI developers then, thanks for the suggestions and the quick answers!

**Comment by flozz** [comment]
I close this issue, please open a new one if you have more questions :)
