### ISSUE TITLE
pysqlite is not supported on Python 3

### ISSUE THREAD

**Issue by walgren** [flozz/pypapi#27]
Hello, I am trying to install pypapi on an anaconda distribution (Spyder version 3.3.3, Python 3.7.3 64-bit, Windows 10), and I get the following callback:
`pip install pypapi`

`pysqlite is not supported on Python 3. When using Python 3, use the sqlite3 module from the standard library.`

Could the installation files be modified on my side, or could the installation files by modified to check for python 2 vs. python 3?

**Comment by flozz** [comment]
Hello,

PyPAPI is just a Python binding for the PAPI C library, the only code in this module is the binding itself so I do not know why you have this error. PyPAPI does not use Sqlite at all and [the only dependency](https://github.com/flozz/pypapi/blob/master/setup.py#L42-L43) it has is [CFFI](https://cffi.readthedocs.io/en/latest/) that do not use it neither...

I realy do not know how to help you, sorry :(

**Comment by walgren** [comment]
Interesting. Here is the full pip output:
`pip install pypapi
Collecting pypapi
  Using cached https://files.pythonhosted.org/packages/06/62/c0f3da41c24bdba75dfdd3cd667a3a67248f356077de01a2ad2e870531bb/pypapi-0.8.tar.gz
Requirement already satisfied: sqlalchemy>=0.5.0rc2 in c:\programdata\anaconda3\lib\site-packages (from pypapi) (1.3.1)
Collecting zope.component>=3.4 (from pypapi)
  Using cached https://files.pythonhosted.org/packages/0d/df/e9f3cf96309dd84f24ad842eb41969bb5085bafb92efb19443f9ddf9beb2/zope.component-5.0.0-py2.py3-none-any.whl
Collecting zope.interface>=3.4 (from pypapi)
  Using cached https://files.pythonhosted.org/packages/c4/60/76c9c07399cbe0bcf53b507938874d038f3b539d15610c60344d4e38f557/zope.interface-5.3.0-cp37-cp37m-win_amd64.whl
Collecting zope.schema>=3.4 (from pypapi)
  Using cached https://files.pythonhosted.org/packages/51/c4/fe58764985099064840d9665dfe66b43aabc0c3b1756657fb4b83c0d0f66/zope.schema-6.1.0-py2.py3-none-any.whl
Collecting ZConfig>=2.5 (from pypapi)
  Using cached https://files.pythonhosted.org/packages/d2/33/533ba4b7e39e8fc16dbdf796a84c57b27956a72103ce4bfe2dd354f9fd2a/ZConfig-3.5.0-py2.py3-none-any.whl
Collecting pysqlite (from pypapi)
  Using cached https://files.pythonhosted.org/packages/42/02/981b6703e3c83c5b25a829c6e77aad059f9481b0bbacb47e6e8ca12bd731/pysqlite-2.8.3.tar.gz
    Complete output from command python setup.py egg_info:
    pysqlite is not supported on Python 3. When using Python 3, use the sqlite3 module from the standard library.
    
    ----------------------------------------
Note: you may need to restart the kernel to use updated packages.
Command "python setup.py egg_info" failed with error code 1 in C:\Users\PWALGR~1\AppData\Local\Temp\pip-install-3qyq7gaz\pysqlite\`

I've reached out to my organization IT as well, so hopefully they've seen this before. Thanks for the quick reply!

**Comment by flozz** [comment]
Oh right, I understood!

The PyPI package for this library is [python_papi](https://pypi.org/project/python_papi/) not [pypapi](https://pypi.org/project/PyPaPi/) that is "A multidatabase descriptive framework for developing application with Python and Qt toolkit"! 

Sadly, the name `pypapi` was not available when I published this package... ^^'

**Comment by flozz** [comment]
(sorry it took me time to understand the problem...)

**Comment by walgren** [comment]
Oh, okay, that makes sense. No wonder it was trying to install seemingly random packages - installing a totally different package will do that. Upon trying to pip install the correct package (pip install python_papi), I get an error that I think is to do with my username being too long:

`LINK : fatal error LNK1181: cannot open input file 'C:\Users\PWALGR~1\AppData\Local\Temp\pip-install-8ll7wv3r\python-papi\pypapi\..\papi\src\libpapi.a'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181`

My username is not PWALGR~1, and I've seen this error in other packages as well. I'm going to try tomorrow to modify the temp directory directly, and will update this thread with what I find. This is a related thread for inkscape: https://gitlab.com/inkscape/extensions/-/issues/287#note_494339913

**Comment by flozz** [comment]
I [searched in the PAPI repository](https://bitbucket.org/icl/papi/commits/?search=windows)... Windows seems to not be actively supported since the v3.7...

![image](https://user-images.githubusercontent.com/971438/113843248-b524b300-9793-11eb-8b25-9edaa4b3b428.png)

And it seems it was dropped since the v5.0 (released in 2012):

```
===============================================================================
PAPI 5.0.0 RELEASE NOTES                                            23 Aug 2012
===============================================================================

[...]

Deprecated:
---------------------
  * Java PAPI wrappers
  * Windows
 ```

The PAPI documentation is not very clear on that... :/

**Comment by flozz** [comment]
I close the issue, please open a new one if you have more questions
